### ISSUE TITLE
Donut disappears with 0 issues

### ISSUE THREAD

**Issue by ryelo** [RedHatInsights/insights-advisor-frontend#177]
![image](https://user-images.githubusercontent.com/12520842/52297031-d1c3c700-294d-11e9-822f-c7e031c9fb43.png)

**Comment by AllenBW** [comment]
is this still an issue @ryelo ? @katierik how should we handle this chart when there is nothing to show? MAYBE A GREEN DONUT THATS 100% 🤷‍♂️

**Comment by katierik** [comment]
If there are 0 things there (which is pretty unlikely in a real scenario based on my understanding of all the use cases) we need to show an empty state. 
I'm hesitant to do a big happy "YOU'RE DONE!" since we can't actually guarantee that they have no issues in their system at all (don't want to give a false sense of security!). What I think makes sense would be an empty state.

The basic outline for how an empty state should look is[ here](https://redhat.invisionapp.com/share/8AQI2U1WQEY#/346694888_ChartCards-NoDataGeneric). 
Of course this needs a little more than just that :)

I added this use case to the [empty state doc for advisor](https://docs.google.com/document/d/1iq1spvMCv3nc1epsv8KqtwuiRbH_6ZMmae53I4aoOWY/edit?usp=sharing), aka on the design backlog.

**Comment by ryelo** [comment]
@AllenBW Yes. If there is still a 0 for all categories, the donut still disappears. 

@katierik Back when we were rolling our own charting, we just used a fully gray donut (almost looks disabled) that said `0 Total hits`

![Screen Shot 2019-03-27 at 8 48 26 AM](https://user-images.githubusercontent.com/12520842/55077002-22fa5800-506d-11e9-9251-fd78cd9e7e94.png)

Not sure if we'd want to do the same here or not.

**Comment by AllenBW** [comment]
![Overview empty states](https://user-images.githubusercontent.com/6640236/55151381-84c9c900-5124-11e9-87dc-4f198c77279f.png)
this is the mock we're gonna fly with
